### ISSUE TITLE
Using wrong variable keyword

### ISSUE THREAD

**Issue by pragmaticAweds** [Khaliid-oh/30_days_of_Js_Lesson#7]
![Screenshot_2023-02-28-07-57-15-019_com android chrome-edit](https://user-images.githubusercontent.com/70960505/221777802-2cce9efb-fcee-4a27-97b0-f4f04fe4e272.jpg)

This is in your exercise, except you are assigning a value to a variable at the first declaration and you are not going to re-assign value to it again, you can use "let" to declare your variable, this variable you created, you didn't give it a variable at first instance because you want to reassign value to it, so you cannot use "const" to declare it instead use "let".

**Comment by Khaliid-oh** [comment]
Alright, thanks
